apiVersion: apps/v1
kind: Deployment
metadata:
  name: rce-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rce
  template:
    metadata:
      labels:
        app: rce
    spec:
      containers:
        - name: rce
          image: victorchrollo14/rce-prod:1.0.1
          imagePullPolicy: Always
          volumeMounts:
            - name: docker-socket
              mountPath: /var/run/docker.sock
            - name: temp-code-volume
              mountPath: /app/temp_code
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
            type: File
        - name: temp-code-volume
          emptyDir:
            sizeLimit: 500Mi
